name: DevOpsBasicsTest-SecondAction
env:
  APPLICATION_NAME : "MyApp"
  DEPLOY_PACKAGE_NAME : "app-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: [ "main" ]
 

jobs:
  myTest:
    runs-on: windows-latest
    steps:
   
    - name: print Hello Message
      run: echo "Hello, world! from myTest job"

    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"


    - name: List current folder
      run: ls

      
    - name: Git Clone my repo
      uses: actions/checkout@v1
    

  myDeploy:
     runs-on: ubuntu-latest
    # needs: [myTest]
    
     env:
       VAR1 : "This is Job Level Variable_1"
       VAR2 : "This is Job Level Variable_2"
       
     steps:

     - name: print env Vars
       run: |
         echo "Var1 = ${{ env.VAR1 }}"
         echo "Var2 = ${{ env.VAR2 }}"
         echo "Var3 = $LOCAL_STEP_VAR
       env:
        LOCAL_STEP_VAR: "This is Super local Env Var"
     
     - name: print Hello Message
       run: echo "Hello, world! from myDeploy job"

     - name: printing Deployment Package
       run: echo "Deploy Package Name is ${{ env.DEPLOY_PACKAGE_NAME }}"

     - name: Let`s test some Packages if they are here 1
       run: aws --version

     - name: Let`s test some Packages if they are here 2
       run: zip
















       
