name: DevOpsBasicsTest-SecondAction

on:
  push:
    branches: [ "main" ]
 

jobs:
  myTest:
    runs-on: windows-latest
    steps:
   
    - name: print Hello Message
      run: echo "Hello, world! from myTest job"

    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"

    - name: List current folder
      run: dir
    

  myDeploy:
     runs-on: windows-latest
     needs: [myTest]
     
     steps:
     
     - name: print Hello Message
       run: echo "Hello, world! from myDeploy job"

















       
